version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    env_file: 
      - .env
    networks:
      - menu_api_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  menu_api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: menu_api
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - menu_api_network

networks:
  menu_api_network:
    driver: bridge
